# Generated by Django 5.1 on 2024-08-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimplePurchase',
        ),
    ]
