# Generated by Django 5.1 on 2024-08-23 18:19

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_purchase_id_purchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_purchase',
            name='purchase',
            field=models.ForeignKey(default=django.db.models.functions.datetime.Now(), null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.purchase'),
        ),
    ]
