# Generated by Django 5.1 on 2024-08-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_item_purchase_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.AddField(
            model_name='purchase',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
