# Generated by Django 5.1 on 2024-08-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_purchase_created_at_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_purchase',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.purchase'),
        ),
    ]
